server:
  host: "0.0.0.0"
  port: 8090
  mode: "release"

# 生产环境 - 使用外部数据库服务
mongodb:
  uri: "mongodb://192.168.7.216:27017"
  database: "stellarserver"  # 生产环境数据库
  user: "admin"
  password: "admin"
  maxPoolSize: 100
  minPoolSize: 10
  maxIdleTimeMS: 30000

redis:
  addr: "192.168.7.128:6379"
  password: "redis"
  db: 0  # 生产环境使用db 0
  poolSize: 100
  minIdleConns: 10
  maxConnAgeMS: 30000

auth:
  jwtSecret: "stellarserver-secret-key"
  tokenExpiry: 24  # 小时

subdomain:
  resolvers:
    - "8.8.8.8:53"
    - "114.114.114.114:53"
  timeout: 10  # 秒
  maxConcurrency: 100
  retryTimes: 3
  dictPath: "./dicts/subdomain_dict.txt"

portscan:
  timeout: 5  # 秒
  rateLimit: 1000  # 每秒请求数
  maxConcurrency: 100
  defaultPorts:
    - 21
    - 22
    - 80
    - 443
    - 3306
    - 6379
    - 8080
    - 8443

vulnscan:
  timeout: 30  # 秒
  maxConcurrency: 50
  pluginPath: "./plugins/vuln"

discovery:
  timeout: 30  # 秒
  maxConcurrency: 50
  scanInterval: 24  # 小时

node:
  heartbeatInterval: 30  # 秒
  heartbeatTimeout: 90  # 秒
  enableAutoRemove: false
  autoRemoveAfter: 86400  # 秒，1天
  masterNodeName: "master-node"

task:
  maxConcurrentTasks: 10
  taskTimeout: 3600  # 秒，1小时
  enableRetry: true
  maxRetries: 3
  retryInterval: 300  # 秒，5分钟
  queueCapacity: 1000
