server:
  host: "0.0.0.0"
  port: 8090
  mode: "debug"
  readTimeout: 30s
  writeTimeout: 30s

# 新的统一数据库配置
database:
  type: "sqlite"  # 开发环境使用SQLite
  path: "./stellar.db"

# MongoDB配置（向后兼容）
mongodb:
  uri: "mongodb://192.168.7.216:27017"
  database: "stellarserver_dev"
  user: "admin"
  password: "admin"
  maxPoolSize: 100
  minPoolSize: 10
  maxIdleTimeMS: 30000

redis:
  addr: "192.168.7.128:6379"
  password: "redis"
  db: 0
  poolSize: 10
  minIdleConns: 5
  maxConnAgeMS: 30000

auth:
  jwtSecret: "stellarserver-dev-secret-key"
  tokenExpiry: 24

subdomain:
  methods:
    - "subfinder"
    - "amass"
  dictionaryPath: "./dicts/subdomain_dict.txt"
  concurrency: 50
  timeout: 10
  retryCount: 3
  rateLimit: 100
  resolverServers:
    - "8.8.8.8:53"
    - "114.114.114.114:53"
  verifySubdomains: true
  checkTakeover: false
  recursiveSearch: false

portscan:
  ports: "1-1000,3000-4000,8000-9000"
  concurrency: 100
  timeout: 5
  retryCount: 3
  rateLimit: 1000
  scanType: "tcp"
  excludeIPs: []

vulnscan:
  timeout: 30
  maxConcurrency: 50
  pluginPath: "./plugins"

discovery:
  timeout: 30
  maxConcurrency: 50
  scanInterval: 24

node:
  heartbeatInterval: 30
  heartbeatTimeout: 90
  enableAutoRemove: false
  autoRemoveAfter: 86400
  masterNodeName: "master-node"

task:
  maxConcurrentTasks: 10
  taskTimeout: 3600
  enableRetry: true
  maxRetries: 3
  retryInterval: 300
  queueCapacity: 1000

logs:
  totalLogs: 1000

system:
  timezone: "Asia/Shanghai"