server:
  host: "0.0.0.0"
  port: 8090
  mode: "debug"

# 测试环境 - 使用外部数据库服务，独立的测试数据库
mongodb:
  uri: "mongodb://192.168.7.216:27017"
  database: "stellarserver_test"  # 测试环境数据库
  user: "admin"
  password: "admin"
  maxPoolSize: 10
  minPoolSize: 2
  maxIdleTimeMS: 10000

redis:
  addr: "192.168.7.128:6379"
  password: "redis"
  db: 2  # 使用db 2作为测试环境
  poolSize: 10
  minIdleConns: 2
  maxConnAgeMS: 10000

auth:
  jwtSecret: "stellarserver-test-secret-key"
  tokenExpiry: 1  # 1小时，测试用

subdomain:
  resolvers:
    - "8.8.8.8:53"
  timeout: 5
  maxConcurrency: 10
  retryTimes: 1
  dictPath: "./dicts/subdomain_dict.txt"

portscan:
  timeout: 3
  rateLimit: 50
  maxConcurrency: 10
  defaultPorts:
    - 80
    - 443

vulnscan:
  timeout: 10
  maxConcurrency: 5
  pluginPath: "./plugins/vuln"

discovery:
  timeout: 10
  maxConcurrency: 5
  scanInterval: 1  # 1小时

node:
  heartbeatInterval: 10
  heartbeatTimeout: 30
  enableAutoRemove: false
  autoRemoveAfter: 3600
  masterNodeName: "test-master-node"

task:
  maxConcurrentTasks: 3
  taskTimeout: 300  # 5分钟
  enableRetry: true
  maxRetries: 1
  retryInterval: 30
  queueCapacity: 50